/**
 * Shared types internal to the bridge layer (`bridge/`).
 *
 * The bridge owns the lifecycle of a private-chat message: bind → derive
 * commandId → dispatch / queue → observe the thread → render → stream the card.
 * These types are the contracts between its modules (session, eventRenderer,
 * turnQueue, outbound, commandId, chatThreadMap).
 */
import type { CommandId, ThreadId, TurnId } from "@t3tools/contracts";

import type { CardElement, CardJson } from "../lark/card.ts";
import type { InboundMessage } from "../lark/types.ts";

// Re-export the lark-layer inbound message so bridge modules depend on
// `bridge/types` for the full set of bridge contracts (queue payloads,
// merge sources) without reaching across into `lark/types`.
export type { InboundMessage };

/**
 * Output of {@link bridge/eventRenderer.renderThreadCard}: the card JSON to
 * push, plus the degradation metadata the renderer computed while keeping every
 * element under Feishu's per-element size limit (~30KB). Pure data — no IO.
 */
export interface RenderResult {
  /** The CardKit 2.0 card JSON to send/update. */
  readonly card: CardJson;
  /**
   * Whether any element was degraded (tool output folded, reasoning truncated,
   * long output trimmed) to stay under the per-element byte ceiling.
   */
  readonly degraded: boolean;
  /** Largest single-element byte estimate after rendering (for diagnostics). */
  readonly maxElementBytes: number;
}

/** Options controlling how a thread is rendered into a card. */
export interface RenderOptions {
  /** Whether the turn is still streaming (drives `streaming_mode`). */
  readonly streaming: boolean;
  /**
   * The turnId of the turn this render belongs to, when the caller knows it.
   *
   * Passed by `driveTurn` (which drives one specific turn) so the
   * tool/reasoning/error/body turn-scoping survives the turn reaching its
   * terminal state: once a turn completes, `thread.session.activeTurnId` flips
   * back to `null`, and without this anchor the final/terminal card would stop
   * filtering and surface the *entire thread's* history. The renderer filters by
   * `currentTurnId ?? thread.session.activeTurnId`, so this only takes effect
   * when provided.
   *
   * Non-`driveTurn` render paths (observeThread mirror-light, notices, recovery
   * echo) have no "this turn" to anchor on and omit it — they keep the existing
   * `activeTurnId` behaviour.
   */
  readonly currentTurnId?: TurnId | null;
  /**
   * Per-element byte ceiling before degradation kicks in. Defaults to the
   * Feishu limit (~30000) when omitted; exposed for testing.
   */
  readonly maxElementBytes?: number;
  /**
   * Pre-rendered interaction section elements (approval buttons, user-input
   * forms, stale notices). Generated by `interactionCard.renderInteractionSection`
   * and injected here so `eventRenderer` stays pure — it has no knowledge of
   * `callbackAuth` or `interactionCard` itself.
   *
   * Each element is passed through the same `clampElement` byte-degradation
   * guard as the other sections before being appended to the card body.
   * Inserted after the tools section and before the error footer.
   */
  readonly interaction?: {
    readonly elements: ReadonlyArray<CardElement>;
  };
}

/**
 * Terminal outcome of an observed turn, derived from the session latch
 * (`status === "running"` seen, then `activeTurnId → null` = success; status in
 * {error, interrupted, stopped} = failure). Consumed by `turnQueue` to know
 * when to flush queued messages, and by the renderer for the final card.
 */
export type TurnOutcome =
  | { readonly kind: "succeeded" }
  | { readonly kind: "failed"; readonly status: string; readonly lastError: string | null };

/**
 * A message held while a turn is running. The bridge merges all queued items
 * for a chat into a single follow-up prompt once the active turn completes
 * (never forwards a second message verbatim — that would steer/overwrite the
 * running agent). See §6 of the M1 spec.
 */
export interface QueuedMessage {
  readonly message: InboundMessage;
  /** Stable commandId derived for this message at enqueue time. */
  readonly commandId: CommandId;
}

/**
 * Resolution of {@link bridge/chatThreadMap.ensureThreadForChat}: the thread
 * bound to a chat, and whether it was just created (first message) versus
 * re-used from a prior binding.
 */
export interface EnsuredThread {
  readonly threadId: ThreadId;
  readonly created: boolean;
}
